### ISSUE TITLE
Todo v1.2.0

### ISSUE THREAD

**Issue by senelway** [senelway/dont-starve-together-cookbook#10]
- [ ] Add favorite list (first step - localstorage)
- [ ] Add recommendation food for season
- [x] Filter by perk only
